name: Deploy to EC2

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'
        cache: 'npm'
        cache-dependency-path: './frontend/package-lock.json'

    - name: Build Vue Frontend
      run: |
        cd frontend
        npm ci
        npm run build

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to EC2
      run: |
        # Copy frontend build
        scp -r frontend/dist/* ubuntu@${{ secrets.EC2_HOST }}:/var/www/inner-sydney-voice/frontend/
        
        # Copy backend code
        scp -r backend/* ubuntu@${{ secrets.EC2_HOST }}:/var/www/inner-sydney-voice/backend/
        
        # Copy deployment scripts
        scp deploy-scripts/* ubuntu@${{ secrets.EC2_HOST }}:/var/www/inner-sydney-voice/
        
        # Execute deployment script on server
        ssh ubuntu@${{ secrets.EC2_HOST }} 'bash /var/www/inner-sydney-voice/deploy.sh'